# Generated by Django 3.2 on 2022-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(1, 'Draft'), (2, 'Published')], max_length=20),
        ),
    ]
