# Generated by Django 3.2 on 2022-05-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20220507_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileattribute',
            name='social_medias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='members.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileattribute',
            name='social',
            field=models.CharField(default='URL', max_length=255),
        ),
    ]
